application: gadget-things
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /gadget
  static_dir: gadget

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
